#arm_torso:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
arm_torso:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  solve_type: Speed
  position_only_ik: false
#arm:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  solve_type: Speed
  position_only_ik: false
sixdof_arm:
 kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
 kinematics_solver_search_resolution: 0.01
 kinematics_solver_timeout: 0.1
 kinematics_solver_attempts: 5
# sixdof_arm:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.1
#   solve_type: Distance
#   position_only_ik: false
