teb/arm_torso:
  group_name: arm_torso
  publish_seed_trajectory: true
  optimization:
    num_timesteps: 30
    initialization_method: 2 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST, 4: FILL_WITH_INITIAL_STATE